services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  admin_service:
    build:
      context: ./admin_service
    container_name: admin_service
    ports:
      - "8001:8001"
    restart: always

  order_service:
    build:
      context: ./order_service
    container_name: order_service
    ports:
      - "8002:8002"
    restart: always

  product_service:
    build:
      context: ./product_service
    container_name: product_service
    ports:
      - "8003:8003"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always

volumes:
  postgres_data: