[app_settings]
app_version='1.0.0'
app_name='lamp'
app_host='localhost'
app_port=8000
app_mount='/api/v1'

[db_settings]
db_name='db_lamp'
db_user='postgres'
db_password='boss'
db_host='localhost'
db_port=5432